### ISSUE TITLE
Error initialising Kubernetes support. "cannot get path "/" and Error running the registration listener

### ISSUE THREAD

**Issue by mitchellmaler** [zalando/zalenium#340]
Hello I am trying to prove out using Zalenium with a k8s environment.  I was able to run Zalenium through docker locally then wanted to start moving it towards a k8s deployment. I followed the samples creating the ServiceAccount, Service, and the Deployment. When the pod tries to start up it gets an error and then doesn't seem to work. I get the error ```User"system:serviceaccount:selenium:zalenium" cannot get path "/"```.  I am running in my own namespace called selenium.

Error:
```
Kubernetes service account found.
-- LOG 23:05:56:180690670 Running additional checks...
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/index.html': No such file or directory
Starting Nginx reverse proxy...
Starting Selenium Hub...
23:05:56.535 INFO - Selenium build info: version: '3.7.1', revision: '8a0099a'
23:05:56.538 INFO - Launching Selenium Grid hub
23:05:56.870 INFO - binding de.zalando.ep.zalenium.servlet.LivePreviewServlet to /grid/admin/LivePreviewServlet/*
23:05:56.873 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet to /grid/admin/ZaleniumConsoleServlet/*
23:05:56.874 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet to /grid/admin/ZaleniumResourceServlet/*
23:05:56.875 INFO - binding de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet to /grid/admin/DashboardCleanupServlet/*
.....2017-11-30 23:05:57 INFO  log:192 - Logging initialized @915ms to org.seleniumhq.jetty9.util.log.Slf4jLog
23:05:57.173 INFO - Will listen on 4445
2017-11-30 23:05:57 INFO  Server:372 - jetty-9.4.5.v20170502
2017-11-30 23:05:57 INFO  session:364 - DefaultSessionIdManager workerName=node0
2017-11-30 23:05:57 INFO  session:369 - No SessionScavenger set, using defaults
2017-11-30 23:05:57 INFO  session:149 - Scavenging every 660000ms
2017-11-30 23:05:57 INFO  ContextHandler:788 - Started o.s.j.s.ServletContextHandler@221af3c0{/,null,AVAILABLE}
2017-11-30 23:05:57 INFO  AbstractConnector:280 - Started ServerConnector@1dd92fe2{HTTP/1.1,[http/1.1]}{0.0.0.0:4445}
2017-11-30 23:05:57 INFO  Server:444 - Started @1072ms
23:05:57.307 INFO - Nodes should register to http://10.2.24.4:4445/grid/register/
23:05:57.308 INFO - Selenium Grid hub is up and running
Selenium Hub started!
Starting DockerSeleniumStarter node...
23:05:57.775 INFO - Selenium build info: version: '3.7.1', revision: '8a0099a'
23:05:57.777 INFO - Launching a Selenium Grid node
2017-11-30 23:05:58.227:INFO::main: Logging initialized @729ms to org.seleniumhq.jetty9.util.log.StdErrLog
23:05:58.275 INFO - Driver class not found: com.opera.core.systems.OperaDriver
23:05:58.305 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities {browserName: internet explorer, ensureCleanSession: true, platform: WINDOWS, version: } does not match the current platform LINUX
23:05:58.306 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities {browserName: MicrosoftEdge, platform: WINDOWS, version: } does not match the current platform LINUX
23:05:58.306 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities {browserName: safari, platform: MAC, version: } does not match the current platform LINUX
23:05:58.352 INFO - Using the passthrough mode handler
2017-11-30 23:05:58.396:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-11-30 23:05:58.424:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@48f2bd5b{/,null,STARTING} has uncovered http methods for path: /
2017-11-30 23:05:58.429:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@48f2bd5b{/,null,AVAILABLE}
2017-11-30 23:05:58.443:INFO:osjs.AbstractConnector:main: Started ServerConnector@45752059{HTTP/1.1,[http/1.1]}{0.0.0.0:30000}
2017-11-30 23:05:58.444:INFO:osjs.Server:main: Started @945ms
23:05:58.444 INFO - Selenium Grid node is up and ready to register to the hub
23:05:58.466 INFO - Registering the node to the hub: http://localhost:4444/grid/register
23:05:58.663 INFO - Initialising Kubernetes support
23:05:59.121 WARN - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:selenium:zalenium" cannot get path "/"..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:236)
	at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:140)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:53)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:37)
	at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:122)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:91)
	at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:35)
	at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.<clinit>(DockerSeleniumStarterRemoteProxy.java:86)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:351)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)
23:05:59.134 INFO - Registered a node http://10.2.24.4:30000
23:05:59.135 INFO - The node is registered to the hub and ready to use
23:05:59.135 INFO - About to clean up any left over selenium pods created by Zalenium
23:05:59.146 ERROR - Error running the registration listener on http://10.2.24.4:30000, null
java.lang.NullPointerException
	at java.util.TreeMap.putAll(TreeMap.java:313)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:433)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:70)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:378)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:357)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.beforeRegistration(DockerSeleniumStarterRemoteProxy.java:385)
	at org.openqa.grid.internal.DefaultGridRegistry.add(DefaultGridRegistry.java:334)
	at org.openqa.grid.web.servlet.RegistrationServlet$1.run(RegistrationServlet.java:110)
	at java.lang.Thread.run(Thread.java:748)
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zalenium
  name: zalenium
  namespace: selenium
spec:
  clusterIP:
  ports:
  - name: zalenium
    nodePort: 31713
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: zalenium
    role: grid
  type: NodePort
```

Deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zalenium
        role: grid
    spec:
      containers:
        - name: zalenium
          image: dosel/zalenium:latest
          args:
            - start
            - '--desiredContainers'
            - '2'
            - '--screenWidth'
            - '1920'
            - '--screenHeight'
            - '1080'
            - '--seleniumImageName'
            - 'elgalu/selenium'
            - '--maxTestSessions'
            - '4'
          env:
            - name: ZALENIUM_KUBERNETES_CPU_REQUEST
              value: 250m
            - name: ZALENIUM_KUBERNETES_CPU_LIMIT
              value: 500m
            - name: ZALENIUM_KUBERNETES_MEMORY_REQUEST
              value: 500Mi
            - name: ZALENIUM_KUBERNETES_MEMORY_LIMIT
              value: 1Gi
            - name: OVERRIDE_WAIT_TIME
              value: 5m
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
          ports:
            - containerPort: 4444
              protocol: TCP
      serviceAccountName: zalenium
      serviceAccount: zalenium
```

**Comment by diemol** [comment]
Hi @mitchellmaler,

Let me check, I think I saw something similar when I deployed in MiniShift. I'll let you know during the weekend.

How do you create your name space?

**Comment by pearj** [comment]
The problem is here `Message: Forbidden!Configured service account doesn't have access.`, that means that you haven't created the zalenium role and added the role to the zalenium service account.

You must be running a version of kubernetes that has Role Based Access Control (RBAC).

I think Kubernetes has had RBAC since 1.7, so I guess you must be running at least that version.

In the kubernetes instructions you need to create a cluster role binding, which basically grants the zalenium-role to the zalenium service account.  See some detail here:

https://kubernetes.io/docs/admin/authorization/rbac/#kubectl-create-clusterrolebinding

The zalenium-role doesn't have to be a cluster role, it's just what I chose when I created it a while back, because I didn't know you could have roles that only applied to the namespace.

One simple way to make it go, would be to give the admin role to the zalenium service account, and not worry about the zalenum-role.  The zalenium-role is simply just the minimum permissions required, whereas admin gives a lot more.

`kubectl create rolebinding zalenium-admin-binding --clusterrole=admin --serviceaccount=selenium:zalenium --namespace=selenium`

That should fix it for you.

**Comment by pearj** [comment]
@diemol, we should probably make minikube use RBAC in Travis so that the RBAC side of things is tested. Looks like you can enable it in minikube by looking here at the bottom https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#examples

**Comment by mitchellmaler** [comment]
@pearj 
I created the role binding but I am still getting the same error when I apply/create the deployment.
```
Name:         zalenium-admin-binding
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  admin
Subjects:
  Kind            Name      Namespace
  ----            ----      ---------
  ServiceAccount  zalenium  selenium
```
```
7:04:38.773 WARN - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:selenium:zalenium" cannot get path "/"
```

**Comment by diemol** [comment]
@mitchellmaler 
I had a similar problem when I was trying to reproduce a bug in OpenShift. The situation was similar, where everything was created in a different name space from the 'default' one.

I had to do this `oc adm policy add-role-to-user zalenium-role -z zalenium --role-namespace='myproject'` 

I guess there is a way to do the same in plain Vanilla k8s, perhaps it is shown here? https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions

I haven't had to deal with that because when we deploy Zalenium here, we do it in "test" clusters, and roles are more flexible there.

**Comment by mitchellmaler** [comment]
A quick question. Why does it say it is trying to do a GET at: https://kubernetes.default.svc/. Since I am running in a namespace shouldn't it be doing a get for that service/namespace instead? I gave both the selenium and zelenium service accounts the admin role but I am still getting the same error.

**Comment by diemol** [comment]
Good point, I see that there is no namespace specified in the deployment. Is that maybe the cause? Or should the deployment get the namespace from the service? Just wondering if the Zalenium pod is getting created in a different namespace.

**Comment by mitchellmaler** [comment]
I can see the pod being created in my selenium namespace. It just keeps failing with that error and being recreated.

**Comment by diemol** [comment]
Could you give us the YAML for the service account, role, name space, etc... ? I would like to reproduce it, maybe we need a change in the code.

**Comment by mitchellmaler** [comment]
Here is the info. The deployment and service are already posted above.

The namespace I didn't create and my co-worker who set it up is out right now and I don't have full cluster admin for this specific k8s environment. Here is the describe for that name space:
```
Name:         selenium
Labels:       <none>
Annotations:  <none>
Status:       Active

No resource quota.

No resource limits.
``` 

For the service account I just ran ```kubectl create serviceaccount zalenium```

I ran the command above to give the role ```kubectl create rolebinding zalenium-admin-binding --clusterrole=admin --serviceaccount=selenium:zalenium --namespace=selenium```

**Comment by joncbender** [comment]
I am having a similar issue, but am running in the default namespace.

[zalenium.yaml.txt](https://github.com/zalando/zalenium/files/1761513/zalenium.yaml.txt)

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"Role","metadata":{"annotations":{},"name":"zalenium","namespace":"default"},"rules":[{"apiGroups":[""],"resources":["endpoints"],"verbs":["get","list","watch","create","update","patch","delete"]}]}
  creationTimestamp: 2018-02-27T05:36:15Z
  name: zalenium
  namespace: default
  resourceVersion: "8734012"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/roles/zalenium
  uid: 20bbbc50-1b80-11e8-80b3-ce8594605e89
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"zalenium","namespace":"default"}}
  creationTimestamp: 2018-02-27T03:11:37Z
  name: zalenium
  namespace: default
  resourceVersion: "8716725"
  selfLink: /api/v1/namespaces/default/serviceaccounts/zalenium
  uid: ec6b9242-1b6b-11e8-80ea-ce8594605e89
secrets:
- name: zalenium-token-5vhsc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"RoleBinding","metadata":{"annotations":{},"name":"zalenium","namespace":"default"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"zalenium"},"subjects":[{"kind":"ServiceAccount","name":"zalenium","namespace":"default"}]}
  creationTimestamp: 2018-02-27T05:36:15Z
  name: zalenium
  namespace: default
  resourceVersion: "8734017"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/rolebindings/zalenium
  uid: 21059cb2-1b80-11e8-80b3-ce8594605e89
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zalenium
subjects:
- kind: ServiceAccount
  name: zalenium
  namespace: default

**Comment by pearj** [comment]
@mitchellmaler Sorry for not responding sooner, I missed these notification emails. 

https://kubernetes.default.svc/ is the kubernetes api server, which runs in the default namespace.  That's what zalenium connects to by default to create pods etc.

I think I figured out what was wrong with the `kubectl create rolebinding zalenium-admin-binding --clusterrole=admin --serviceaccount=selenium:zalenium --namespace=selenium` command.  I just realised I gave you a ClusterRole binding, which is not what we want, we want a regular role.  Because admin is a namespace role, not a cluster role.

So in theory `kubectl create rolebinding zalenium-admin-binding --role=admin --serviceaccount=selenium:zalenium --namespace=selenium` should work, note `--clusterrole` is now `--role`.

If you wanted to use a cluster role, you could use `cluster-admin`, but that would give zalenium access to do anything in your kubernetes cluster, which is not exactly ideal ;).

**Comment by pearj** [comment]
@joncbender what flavour of kubernetes are you using? Minikube? OpenShift? GCE? Others?

**Comment by joncbender** [comment]
@pearj vanilla on proxmox hosted ubuntu VMs.  Let me paste the entire log
```
Kubernetes service account found.                                                                          
-- LOG 12:09:39:378765146 Running additional checks...                                                         
Copying files for Dashboard...                                                                             
Starting Nginx reverse proxy...                                                                            
Starting Selenium Hub...                                                                                   
12:09:41.916 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'                     
12:09:41.927 INFO - Launching Selenium Grid hub on port 4445                     
12:09:43.896 INFO - binding de.zalando.ep.zalenium.servlet.LivePreviewServlet to /grid/admin/LivePreviewServlet/*
12:09:43.900 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet to /grid/admin/ZaleniumConsoleServlet/*
12:09:43.907 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet to /grid/admin/ZaleniumResourceServlet/*
12:09:43.914 INFO - binding de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet to /grid/admin/DashboardCleanupServlet/*
12:09:43.921 INFO - binding de.zalando.ep.zalenium.servlet.VncAuthenticationServlet to /grid/admin/VncAuthenticationServlet/*
............2018-02-27 12:09:44 INFO  log:192 - Logging initialized @4517ms to org.seleniumhq.jetty9.util.log.Slf4jLog
.2018-02-27 12:09:44 INFO  Server:373 - jetty-9.4.7.v20170914, build timestamp: 2017-11-21T22:27:37+01:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-02-27 12:09:45 INFO  session:364 - DefaultSessionIdManager workerName=node0
2018-02-27 12:09:45 INFO  session:369 - No SessionScavenger set, using defaults
2018-02-27 12:09:45 INFO  session:149 - Scavenging every 660000ms                           
2018-02-27 12:09:45 INFO  ContextHandler:788 - Started o.s.j.s.ServletContextHandler@2b6856dd{/,null,AVAILABLE}
2018-02-27 12:09:45 INFO  AbstractConnector:288 - Started ServerConnector@60b76adc{HTTP/1.1,[http/1.1]}{0.0.0.0:4445}
2018-02-27 12:09:45 INFO  Server:410 - Started @5189ms                 
12:09:45.247 INFO - Selenium Grid hub is up and running                
12:09:45.249 INFO - Nodes should register to http://10.233.105.12:4445/grid/register/
12:09:45.250 INFO - Clients should connect to http://10.233.105.12:4445/wd/hub
Selenium Hub started!
Starting DockerSeleniumStarter node...
12:09:47.967 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
12:09:47.975 INFO - Launching a Selenium Grid node on port 30000
2018-02-27 12:09:50.110:INFO::main: Logging initialized @4342ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-02-27 12:09:50.522:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T22:27:37+01:00, git hash: 82b8fb23f757335bb3329d540ce37a2a261
5f0a8
2018-02-27 12:09:50.615:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@1dde4cb2{/,null,STARTING} has uncovered http methods for p
ath: /
2018-02-27 12:09:50.634:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@1dde4cb2{/,null,AVAILABLE}
2018-02-27 12:09:50.753:INFO:osjs.AbstractConnector:main: Started ServerConnector@65eb93d{HTTP/1.1,[http/1.1]}{0.0.0.0:30000}
2018-02-27 12:09:50.754:INFO:osjs.Server:main: Started @4985ms
12:09:50.754 INFO - Selenium Server is up and running on port 30000
12:09:50.756 INFO - Selenium Grid node is up and ready to register to the hub
12:09:50.832 INFO - Registering the node to the hub: http://localhost:4444/grid/register
12:09:51.787 INFO - Initialising Kubernetes support
12:09:55.299 WARN - Error initialising Kubernetes support.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/. Message: Forbidden!Configured service accou
nt doesn't have access. Service account may have been revoked. forbidden: User "system:serviceaccount:default:zalenium" cannot get path "/".
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:236)
        at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:140)
        at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:53)
        at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:37)
        at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:122)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.<init>(KubernetesContainerClient.java:84)
        at de.zalando.ep.zalenium.container.ContainerFactory.createKubernetesContainerClient(ContainerFactory.java:35)
        at de.zalando.ep.zalenium.container.ContainerFactory.getContainerClient(ContainerFactory.java:22)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.<clinit>(DockerSeleniumStarterRemoteProxy.java:93)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:361)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:71)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
      at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)
12:09:55.387 INFO - Registered a node http://10.233.105.12:30000
12:09:55.391 INFO - About to clean up any left over selenium pods created by Zalenium
12:09:55.407 INFO - Updating the node configuration from the hub
12:09:55.431 ERROR - Error running the registration listener on http://10.233.105.12:30000, null
java.lang.NullPointerException
        at java.util.TreeMap.putAll(TreeMap.java:313)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:433)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withLabels(BaseOperation.java:70)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.deleteSeleniumPods(KubernetesContainerClient.java:367)
        at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.initialiseContainerEnvironment(KubernetesContainerClient.java:346)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy.beforeRegistration(DockerSeleniumStarterRemoteProxy.java:407)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.add(ZaleniumRegistry.java:285)
        at org.openqa.grid.web.servlet.RegistrationServlet$1.run(RegistrationServlet.java:110)
        at java.lang.Thread.run(Thread.java:748)
12:09:55.512 INFO - The node is registered to the hub and ready to use
```

**Comment by pearj** [comment]
@joncbender I’m yet to actually try the kubernetes rbac support, I’ve only tried the OpenShift rbac before it was merged into kubernetes. 

Can you try using the admin role like this:
`kubectl create rolebinding zalenium-admin-binding --role=admin --serviceaccount=default:zalenium --namespace=default`

Once that works I’ll try and figure out what is wrong with the zalenium role in kubernetes rbac

**Comment by joncbender** [comment]
@pearj No luck, unfortunately.

In the API server logs, I see:

```
kube02:I0228 01:45:09.976530       1 rbac.go:116] RBAC DENY: user "system:serviceaccount:default:zalenium" groups ["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"] cannot "get" nonResourceURL "/" cluster-wide
```
With that in mind, I added a new clusterrole and binding:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zalenium-nonresource
rules:
        - nonResourceURLs: [""]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zalenium-nonresource
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zalenium
subjects:
- kind: ServiceAccount
  name: zalenium
  namespace: default
---```

This also has no affect

**Comment by joncbender** [comment]
I adjusted my roles to:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zalenium
  namespace: default
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zalenium-nonresource
  namespace: default
rules:
        - nonResourceURLs: ["*"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
From inside the pod I can now do:
```
curl -ik \
     -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
     https://kubernetes.default.svc.cluster.local/api/v1/namespaces/default/pods

curl -ik \
     -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
     https://kubernetes.default.svc.cluster.local/api/
```
However, the following:
```
curl -ik      -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"      https://kubernets.default.svc.cluster.local/
```
gives me the same error as above:
```
kube02:I0228 01:02:57.116959       1 rbac.go:116] RBAC DENY: user "system:serviceaccount:default:zalenium" groups ["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"] cannot "get" nonResourceURL "/" cluster-wide
```

**Comment by pearj** [comment]
Oh I see it’s looking for nonResourceURL of “/“ it sounds like the
KubernetesClient must be trying to check if the URL exists or something.

If you look at
https://kubernetes.io/docs/admin/authorization/rbac/#role-examples

And search for nonResourceURL it sounds like you probably need to allow get
for “/“

**Comment by mitchellmaler** [comment]
@pearj Thanks for that! Ill have to give it go!
I have learned way more about k8s since then so it makes a lot more sense now what was the issue!

We are moving providers for our k8s env so it may be a bit before I can give it a go.

**Comment by joncbender** [comment]
@pearj Based on https://github.com/fabric8io/kubernetes-client/issues/850
I added 
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zalenium-cluster-admin-resource
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: zalenium
  namespace: default
```

Everything works now.

**Comment by pearj** [comment]
cluster-admin isn't really what we want though. If the problem is simply related to isOpenshift, I think we can remove that check from Zalenium, because in the end I didn't end up using any features that required openshift specifically.

**Comment by pearj** [comment]
I had a look at how isOpenShift works:

https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java#L48

And it does traverse the API server from the base, so it probably needs some "nonResourceURL" permissions to be able to do that.  However, it's still probably simpler just to remove the openshift detecting.

**Comment by diemol** [comment]
Thanks to @pearj's PR that has been merge to master this should work, I'll do the release tomorrow and then we would appreciate feedback on it.

**Comment by joncbender** [comment]
@diemol @pearj 
Sorry for the delay, but I've just now had a chance to do a quick test with the 3.11.0a release.  Definitely fixed the permission issue.  

/grid/register does throw some exceptions, but that may just be my configuration.  I'll look into that later and open another issue if needed.

**Comment by diemol** [comment]
@joncbender Thanks for the feedback!
